export const TRIVIA_QUESTIONS = [
  // Teoría [0-49]
  { q: "¿Cuántas líneas tiene un pentagrama?", options: ["4", "5", "6", "7"], correct: 1, difficulty: "facil" },
  { q: "¿Qué figura musical dura 4 tiempos en 4/4?", options: ["Blanca", "Negra", "Redonda", "Corchea"], correct: 2, difficulty: "facil" },
  { q: "¿Qué símbolo eleva medio tono una nota?", options: ["Bemol", "Becuadro", "Calderón", "Sostenido"], correct: 3, difficulty: "facil" },
  { q: "¿Qué significa la indicación 'Forte' (f)?", options: ["Tocar rápido", "Tocar fuerte", "Tocar suave", "Parar"], correct: 1, difficulty: "facil" },
  { q: "¿Cuántos tiempos dura una blanca con puntillo?", options: ["1", "2", "3", "4"], correct: 2, difficulty: "medio" },
  { q: "¿Qué clave lee normalmente el bajo eléctrico?", options: ["Sol", "Fa", "Do", "Re"], correct: 1, difficulty: "medio" },
  { q: "¿Cuál es el tempo habitual de una balada?", options: ["60-80 BPM", "120-140 BPM", "160-180 BPM", "200+ BPM"], correct: 0, difficulty: "medio" },
  { q: "¿Qué intervalo hay entre Do y Mi?", options: ["Segunda", "Tercera", "Cuarta", "Quinta"], correct: 1, difficulty: "facil" },
  { q: "¿Qué significa 'Crescendo'?", options: ["Tocar rápido", "Bajar volumen", "Subir volumen", "Ir al inicio"], correct: 2, difficulty: "facil" },
  { q: "¿Cuál de estos tempos es más rápido?", options: ["Adagio", "Andante", "Allegro", "Presto"], correct: 3, difficulty: "medio" },
  { q: "¿Cuántos semitonos componen una octava?", options: ["8", "10", "12", "14"], correct: 2, difficulty: "medio" },
  { q: "¿Qué nota es la 'A' en cifrado americano?", options: ["Do", "Fa", "Sol", "La"], correct: 3, difficulty: "facil" },
  { q: "¿Qué figura equivale a la mitad de una negra?", options: ["Blanca", "Corchea", "Semicorchea", "Redonda"], correct: 1, difficulty: "facil" },
  { q: "¿Qué acorde forman Do, Mi y Sol?", options: ["Do Menor", "Do Mayor", "Do Aumentado", "Sol Mayor"], correct: 1, difficulty: "medio" },
  { q: "¿Cómo se llama el silencio de 4 tiempos?", options: ["De Negra", "De Blanca", "De Redonda", "De Corchea"], correct: 2, difficulty: "facil" },
  { q: "¿Qué nota está un tono por debajo de Re?", options: ["Do", "Do#", "Si", "Mib"], correct: 0, difficulty: "facil" },
  { q: "¿Qué es un arpegio?", options: ["Notas de acorde tocadas una a una", "Un tipo de guitarra", "Cantar alto", "Silencio largo"], correct: 0, difficulty: "medio" },
  { q: "¿Cuál es la quinta justa de La (A)?", options: ["Re", "Mi", "Fa", "Sol"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué indica el número superior de un compás?", options: ["Nota base", "Cantidad de pulsos", "Duración", "Velocidad"], correct: 1, difficulty: "medio" },
  { q: "¿Qué escala tiene la estructura T-T-ST-T-T-T-ST?", options: ["Menor", "Mayor", "Pentatónica", "Dórica"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué acorde es relativo menor de Do Mayor?", options: ["La Menor", "Mi Menor", "Re Menor", "Fa Menor"], correct: 0, difficulty: "medio" },
  { q: "¿Qué tipo de compás es un Vals?", options: ["2/4", "3/4", "4/4", "6/8"], correct: 1, difficulty: "medio" },
  { q: "¿Cuántos tonos hay de la primera a la quinta en escala mayor?", options: ["3 y medio", "2 y medio", "4", "3"], correct: 0, difficulty: "dificil" },
  { q: "¿Cuál es la nota central (C4) en un piano?", options: ["Do Central", "Mi Central", "La Central", "Re Central"], correct: 0, difficulty: "facil" },
  { q: "¿Qué modo suele sonar triste o melancólico?", options: ["Modo Mayor", "Modo Menor", "Modo Lidio", "Mixolidio"], correct: 1, difficulty: "facil" },
  { q: "¿Qué frecuencia (Hz) afina el La estándar (A4)?", options: ["432 Hz", "440 Hz", "444 Hz", "450 Hz"], correct: 1, difficulty: "medio" },
  { q: "¿Qué escala tiene 5 notas?", options: ["Diatónica", "Pentatónica", "Cromática", "Octatónica"], correct: 1, difficulty: "facil" },
  { q: "¿Qué nota es 'C' en cifrado americano?", options: ["Do", "Si", "La", "Re"], correct: 0, difficulty: "facil" },
  { q: "¿Qué obtenemos si subimos un tono a Fa?", options: ["Sol", "Fa Sostenido", "Mi", "La"], correct: 0, difficulty: "medio" },
  { q: "¿Qué es la armonía?", options: ["El ritmo", "Superposición de acordes", "La melodía sola", "El silencio"], correct: 1, difficulty: "medio" },
  { q: "¿Qué nota es 'F'?", options: ["Sol", "Fa", "Mi", "Si"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es un ostinato?", options: ["Un final", "Patrón musical repetido", "Un grito", "Un error"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué nota es 'G'?", options: ["Sol", "La", "Si", "Fa"], correct: 0, difficulty: "facil" },
  { q: "¿Qué es el compás de amalgama?", options: ["4/4", "7/4", "3/4", "2/4"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué es una síncopa?", options: ["Acentuar el tiempo débil", "Tocar muy alto", "Bajar el tempo", "Silencio de negra"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué nota es la dominante en Do Mayor?", options: ["Fa", "Sol", "La", "Re"], correct: 1, difficulty: "medio" },
  { q: "¿Qué acorde es G7?", options: ["Sol Menor", "Sol Mayor con Séptima Menor", "Sol Aumentado", "Sol Mayor 7"], correct: 1, difficulty: "dificil" },
  { q: "¿Cuál es la primera nota de Mi bemol Mayor?", options: ["Re#", "Mib", "Mi", "Fa"], correct: 1, difficulty: "facil" },
  { q: "¿Qué indica la clave de Fa?", options: ["Notas agudas", "Notas graves", "Ritmo", "Volumen"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es un tritono?", options: ["3 notas", "3 tonos exactos", "Un acorde mayor", "Una escala menor"], correct: 1, difficulty: "medio" },
  { q: "¿Qué nota es 'E'?", options: ["Do", "Re", "Mi", "Fa"], correct: 2, difficulty: "facil" },
  { q: "¿Qué es la anacrusa?", options: ["Instrumento griego", "Empezar antes del primer tiempo", "Final brusco", "Coro agudo"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué significa 'Pianissimo'?", options: ["Suave", "Muy suave", "Rápido", "Lento"], correct: 1, difficulty: "facil" },
  { q: "¿A qué nota corresponde el 3er espacio del pentagrama (Sol)?", options: ["Si", "Do", "Re", "La"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué es un calderón?", options: ["Prolonga la duración de la nota", "Sube el tono", "Silencio", "Instrumento"], correct: 0, difficulty: "medio" },
  { q: "¿Qué es el puente en una canción?", options: ["Final", "Conexión entre estrofa y estribillo", "Inicio", "Solo"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es un acorde menor?", options: ["Alegre", "Triste", "Rápido", "Largo"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es la escala cromática?", options: ["5 notas", "12 semitonos", "7 notas", "8 notas"], correct: 1, difficulty: "medio" },
  { q: "¿Qué nota es 'D'?", options: ["Do", "Re", "Mi", "Fa"], correct: 1, difficulty: "facil" },
  { q: "¿Qué significa BPM?", options: ["Bajos Por Minuto", "Beats Per Minute", "Batería Para Músicos", "Bien Por Mí"], correct: 1, difficulty: "facil" },

  // Instrumentos [50-99]
  { q: "¿Cuántas cuerdas tiene la guitarra clásica?", options: ["4", "5", "6", "7"], correct: 2, difficulty: "facil" },
  { q: "¿Cuál de estos NO es de percusión?", options: ["Cajón", "Xilófono", "Oboe", "Timbal"], correct: 2, difficulty: "facil" },
  { q: "¿Cómo se llama el palito del violín?", options: ["Batuta", "Arco", "Baqueta", "Púa"], correct: 1, difficulty: "facil" },
  { q: "¿Cuántas cuerdas tiene un bajo estándar?", options: ["4", "5", "6", "8"], correct: 0, difficulty: "facil" },
  { q: "¿De qué madera suele ser el diapasón oscuro de la guitarra?", options: ["Pino", "Palo Rosa", "Bambú", "Roble"], correct: 1, difficulty: "medio" },
  { q: "¿Qué platillo doble se abre con el pie?", options: ["Crash", "Ride", "Hi-hat", "Splash"], correct: 2, difficulty: "medio" },
  { q: "¿Cuántas teclas tiene un piano estándar?", options: ["61", "76", "88", "102"], correct: 2, difficulty: "medio" },
  { q: "¿Qué voz femenina es la más aguda?", options: ["Contralto", "Mezzo", "Soprano", "Tenor"], correct: 2, difficulty: "facil" },
  { q: "¿Qué afloja o tensa las cuerdas de guitarra?", options: ["Puente", "Trastes", "Clavijas", "Pastillas"], correct: 2, difficulty: "facil" },
  { q: "¿Qué instrumento da la nota más grave en la orquesta?", options: ["Fagot", "Tuba", "Contrabajo", "Violonchelo"], correct: 2, difficulty: "medio" },
  { q: "¿Qué micro es ideal para grabar voces en estudio?", options: ["Dinámico", "De condensador", "De cinta", "Lavalier"], correct: 1, difficulty: "medio" },
  { q: "¿Afinación estándar de la 6ª cuerda de guitarra?", options: ["Mi", "La", "Re", "Sol"], correct: 0, difficulty: "medio" },
  { q: "¿Qué parte de la batería suena más grave?", options: ["Caja", "Bombo", "Tom base", "Ride"], correct: 1, difficulty: "facil" },
  { q: "¿Qué músculo es vital para el canto?", options: ["Abdomen", "Diafragma", "Laringe", "Tráquea"], correct: 1, difficulty: "facil" },
  { q: "¿Cuántas cuerdas tiene un ukelele?", options: ["4", "5", "6", "8"], correct: 0, difficulty: "facil" },
  { q: "¿Qué capta el sonido en la guitarra eléctrica?", options: ["Mástil", "Clavijero", "Pastillas", "Jack"], correct: 2, difficulty: "facil" },
  { q: "¿Qué técnica de bajo popularizó Flea (RHCP)?", options: ["Tapping", "Slap", "Fingerpicking", "Sweep"], correct: 1, difficulty: "medio" },
  { q: "¿Qué pedal sube y baja frecuencias como una voz?", options: ["Fuzz", "Wah-Wah", "Phaser", "Flanger"], correct: 1, difficulty: "medio" },
  { q: "¿Qué instrumento es de viento-madera pero hecho de metal?", options: ["Trompeta", "Trombón", "Flauta Travesera", "Clarinete"], correct: 2, difficulty: "medio" },
  { q: "¿Cómo se llama tocar dos notas a la vez en guitarra?", options: ["Trémolo", "Bending", "Double Stop", "Slide"], correct: 2, difficulty: "dificil" },
  { q: "¿Qué significa 'Pizzicato'?", options: ["Tocar fuerte", "Pellizcar cuerdas frotadas", "Usar arco", "Acordes"], correct: 1, difficulty: "medio" },
  { q: "¿Qué técnica de metal rasga la voz?", options: ["Falsete", "Vibrato", "Growl", "Melisma"], correct: 2, difficulty: "medio" },
  { q: "¿Qué hueso apoya las cuerdas en el clavijero?", options: ["Cejuela", "Puente", "Alma", "Traste cero"], correct: 0, difficulty: "medio" },
  { q: "¿Qué instrumento tocaba Miles Davis?", options: ["Guitarra", "Bajo", "Piano", "Trompeta"], correct: 3, difficulty: "facil" },
  { q: "¿Qué es un metrónomo?", options: ["Afinador", "Marca el pulso", "Efecto", "Llave de batería"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es el 'Vibrato'?", options: ["Subir volumen", "Oscilar altura del sonido", "Tocar rápido", "Silenciar"], correct: 1, difficulty: "medio" },
  { q: "¿Cuántas llaves suele tener un saxo moderno?", options: ["15", "22", "30", "40+"], correct: 1, difficulty: "dificil" },
  { q: "¿Cómo se llama la pequeña pieza para tocar guitarra?", options: ["Arco", "Baqueta", "Púa", "Cejilla"], correct: 2, difficulty: "facil" },
  { q: "¿Qué tipo de bajo no tiene trastes?", options: ["Acústico", "Fretless", "Contrabajo", "De 6 cuerdas"], correct: 1, difficulty: "facil" },
  { q: "¿Qué significa 'Glissando'?", options: ["Tocar fuerte", "Deslizar de una nota a otra", "Silencio", "Repetir"], correct: 1, difficulty: "medio" },
  { q: "¿Cómo se llama la técnica de cantar varias notas por sílaba?", options: ["Vibrato", "Melisma", "Falsete", "Belt"], correct: 1, difficulty: "dificil" },
  { q: "¿A qué familia pertenece el Saxofón?", options: ["Metal", "Madera", "Percusión", "Cuerda"], correct: 1, difficulty: "medio" },
  { q: "¿Qué instrumento tocaba Ravi Shankar?", options: ["Sitar", "Guitarra", "Arpa", "Violín"], correct: 0, difficulty: "medio" },
  { q: "¿Parte del arco de violín que se sujeta?", options: ["Punta", "Nuez", "Cerdas", "Vara"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué instrumento toca Yo-Yo Ma?", options: ["Violín", "Viola", "Violonchelo", "Contrabajo"], correct: 2, difficulty: "medio" },
  { q: "¿Qué parte de la batería da el 'backbeat' en rock?", options: ["Caja", "Tom", "Bombo", "Splash"], correct: 0, difficulty: "medio" },
  { q: "¿Cuántos trastes tiene una eléctrica estándar?", options: ["12-15", "21-24", "28-30", "10-12"], correct: 1, difficulty: "medio" },
  { q: "¿Qué instrumento tocaba Louis Armstrong?", options: ["Saxo", "Trompeta", "Trombón", "Clarinete"], correct: 1, difficulty: "facil" },
  { q: "¿Qué instrumento es un Stradivarius?", options: ["Piano", "Violín", "Guitarra", "Flauta"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es una partitura?", options: ["Instrumento", "Escritura musical", "Concierto", "Músico"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es el timbre?", options: ["Volumen", "Color del sonido", "Altura", "Duración"], correct: 1, difficulty: "medio" },
  { q: "¿Qué instrumento usa sordina?", options: ["Piano", "Trompeta", "Batería", "Guitarra"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es el 'gain' en un ampli?", options: ["Volumen", "Saturación/Distorsión", "Agudos", "Graves"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es un riff?", options: ["Un error", "Frase pegadiza de guitarra", "Platillo", "Cantante"], correct: 1, difficulty: "facil" },
  { q: "¿Qué madera es común en el cuerpo de guitarras acústicas?", options: ["Ébano", "Pino", "Caoba/Abeto", "Bambú"], correct: 2, difficulty: "dificil" },
  { q: "¿Qué micrófono no necesita alimentación extra (Phantom)?", options: ["Condensador", "Dinámico", "De válvula", "De cinta"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es el 'Palm Mute'?", options: ["Mutear con la palma de la mano", "Afinar", "Cambiar pastillas", "Romper la púa"], correct: 0, difficulty: "facil" },
  { q: "¿Qué batería tiene los parches de malla?", options: ["Acústica", "Electrónica", "Sinfónica", "Timbales"], correct: 1, difficulty: "medio" },
  { q: "¿Qué pedal duplica tu sonido como si hubiera otra guitarra?", options: ["Distorsión", "Chorus", "Wah", "Compresor"], correct: 1, difficulty: "medio" },

  // Cultura General e Historia [100-149]
  { q: "¿Quién compuso 'Las cuatro estaciones'?", options: ["Mozart", "Beethoven", "Vivaldi", "Bach"], correct: 2, difficulty: "facil" },
  { q: "¿Qué instrumento tocaba Jimi Hendrix?", options: ["Bajo", "Batería", "Teclado", "Guitarra"], correct: 3, difficulty: "facil" },
  { q: "¿Qué estilo tiene ritmo 'swing' y mucha improvisación?", options: ["Reggae", "Jazz", "Metal", "Cumbia"], correct: 1, difficulty: "facil" },
  { q: "¿Qué significa 'A cappella'?", options: ["Agudo", "Sin instrumentos", "En latín", "Rápido"], correct: 1, difficulty: "facil" },
  { q: "¿Quién es el 'Rey del Pop'?", options: ["Elvis", "Prince", "Michael Jackson", "Freddie Mercury"], correct: 2, difficulty: "facil" },
  { q: "¿Qué banda cruzó el paso de Abbey Road?", options: ["Stones", "The Who", "The Beatles", "Pink Floyd"], correct: 2, difficulty: "facil" },
  { q: "¿Qué compositor se quedó sordo?", options: ["Beethoven", "Chopin", "Tchaikovsky", "Wagner"], correct: 0, difficulty: "facil" },
  { q: "¿De dónde es el Flamenco?", options: ["Argentina", "México", "España", "Cuba"], correct: 2, difficulty: "facil" },
  { q: "¿Qué banda lideraba Freddie Mercury?", options: ["AC/DC", "Queen", "Nirvana", "Guns N' Roses"], correct: 1, difficulty: "facil" },
  { q: "¿Cuándo fue el festival de Woodstock original?", options: ["1950s", "1960s (1969)", "1970s", "1980s"], correct: 1, difficulty: "medio" },
  { q: "¿Qué estilo popularizó Bob Marley?", options: ["Salsa", "Jazz", "Reggae", "Bossa Nova"], correct: 2, difficulty: "facil" },
  { q: "¿Vocalista de The Doors?", options: ["Jim Morrison", "Mick Jagger", "Robert Plant", "Kurt Cobain"], correct: 0, difficulty: "medio" },
  { q: "¿De qué ciudad son The Beatles?", options: ["Londres", "Manchester", "Liverpool", "Birmingham"], correct: 2, difficulty: "facil" },
  { q: "¿Quién es 'La Reina del Soul'?", options: ["Whitney Houston", "Aretha Franklin", "Tina Turner", "Diana Ross"], correct: 1, difficulty: "facil" },
  { q: "¿Dónde nació el Jazz?", options: ["Inglaterra", "Francia", "Estados Unidos", "Brasil"], correct: 2, difficulty: "facil" },
  { q: "¿Qué guitarrista tocaba en Led Zeppelin?", options: ["Clapton", "Jimmy Page", "Keith Richards", "Slash"], correct: 1, difficulty: "medio" },
  { q: "¿Autor de BSO de 'Star Wars' y 'Jurassic Park'?", options: ["Zimmer", "John Williams", "Morricone", "Elfman"], correct: 1, difficulty: "facil" },
  { q: "¿Quién canta 'Thriller'?", options: ["Prince", "Stevie Wonder", "Michael Jackson", "George Michael"], correct: 2, difficulty: "facil" },
  { q: "¿Qué estilo es famoso en Nueva Orleans?", options: ["Country", "Jazz", "Grunge", "Punk"], correct: 1, difficulty: "medio" },
  { q: "¿Qué instrumento toca Carlos Santana?", options: ["Guitarra", "Batería", "Piano", "Bajo"], correct: 0, difficulty: "facil" },
  { q: "¿Fabricante de la 'Stratocaster'?", options: ["Gibson", "Ibanez", "Fender", "PRS"], correct: 2, difficulty: "facil" },
  { q: "¿Baterista de The Who que destruía su set?", options: ["John Bonham", "Ringo Starr", "Keith Moon", "Neil Peart"], correct: 2, difficulty: "medio" },
  { q: "¿Compositor del Himno de la Alegría?", options: ["Mozart", "Beethoven", "Brahms", "Wagner"], correct: 1, difficulty: "facil" },
  { q: "¿Banda de Kurt Cobain?", options: ["Pearl Jam", "Alice in Chains", "Nirvana", "Soundgarden"], correct: 2, difficulty: "facil" },
  { q: "¿Estilo de los 70 nacido como rebelión al rock progresivo?", options: ["Disco", "Punk", "Metal", "New Wave"], correct: 1, difficulty: "medio" },
  { q: "¿Quién tocaba el bajo en los Beatles?", options: ["Lennon", "Harrison", "Starr", "McCartney"], correct: 3, difficulty: "facil" },
  { q: "¿Ritmo base del Reggaetón?", options: ["Dem Bow", "Tumbao", "Clave", "Swing"], correct: 0, difficulty: "medio" },
  { q: "¿Quién es 'The Boss'?", options: ["Bruce Springsteen", "Elvis Presley", "Frank Sinatra", "David Bowie"], correct: 0, difficulty: "facil" },
  { q: "¿Banda del disco 'The Dark Side of the Moon'?", options: ["The Doors", "Pink Floyd", "The Clash", "Led Zeppelin"], correct: 1, difficulty: "medio" },
  { q: "¿Compositor de la 'Marcha Turca'?", options: ["Beethoven", "Chopin", "Mozart", "Tchaikovsky"], correct: 2, difficulty: "medio" },
  { q: "¿Cantante protagonista de 'El Guardaespaldas'?", options: ["Mariah Carey", "Celine Dion", "Whitney Houston", "Tina Turner"], correct: 2, difficulty: "facil" },
  { q: "¿Banda de 'Smells Like Teen Spirit'?", options: ["Oasis", "Nirvana", "Green Day", "Radiohead"], correct: 1, difficulty: "facil" },
  { q: "¿País de la 'Bossa Nova'?", options: ["México", "España", "Brasil", "Perú"], correct: 2, difficulty: "facil" },
  { q: "¿Director de orquesta?", options: ["Compositor", "Maestro", "Concertino", "Arreglista"], correct: 1, difficulty: "facil" },
  { q: "¿Instrumento de Paco de Lucía?", options: ["Bajo", "Batería", "Piano", "Guitarra"], correct: 3, difficulty: "facil" },
  { q: "¿Banda de Chris Martin?", options: ["Keane", "Coldplay", "Muse", "Arctic Monkeys"], correct: 1, difficulty: "facil" },
  { q: "¿Autor de 'Rocket Man'?", options: ["Elton John", "Billy Joel", "McCartney", "Bowie"], correct: 0, difficulty: "medio" },
  { q: "¿Género nacido en el Bronx en los 70?", options: ["Rock", "Techno", "Hip Hop", "Salsa"], correct: 2, difficulty: "medio" },
  { q: "¿Guitarra que usa Angus Young (AC/DC)?", options: ["Stratocaster", "Gibson SG", "Les Paul", "Ibanez"], correct: 1, difficulty: "dificil" },
  { q: "¿Canta 'Like a Prayer'?", options: ["Madonna", "Aretha", "Whitney", "Cher"], correct: 0, difficulty: "facil" },
  { q: "¿Artista ciego desde niño?", options: ["Ray Charles", "Stevie Wonder", "Andrea Bocelli", "Todos ellos"], correct: 3, difficulty: "facil" },
  { q: "¿Compositor barroco con 20 hijos?", options: ["Vivaldi", "Bach", "Mozart", "Händel"], correct: 1, difficulty: "medio" },
  { q: "¿Compositor de sistema dodecafónico?", options: ["Schoenberg", "Stravinsky", "Debussy", "Ravel"], correct: 0, difficulty: "dificil" },
  { q: "¿Bajista de Iron Maiden?", options: ["Steve Harris", "Lemmy", "Cliff Burton", "Geezer"], correct: 0, difficulty: "dificil" },
  { q: "¿Banda de 'Stairway to Heaven'?", options: ["Pink Floyd", "Led Zeppelin", "Deep Purple", "The Doors"], correct: 1, difficulty: "facil" },
  { q: "¿Autor de 'El Mesías'?", options: ["Bach", "Händel", "Vivaldi", "Telemann"], correct: 1, difficulty: "medio" },
  { q: "¿Banda del álbum 'Nevermind'?", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Alice"], correct: 1, difficulty: "facil" },
  { q: "¿Quién canta 'Purple Rain'?", options: ["Michael Jackson", "Prince", "David Bowie", "Madonna"], correct: 1, difficulty: "facil" },
  { q: "¿Rey del Blues?", options: ["B.B. King", "Muddy Waters", "Robert Johnson", "Buddy Guy"], correct: 0, difficulty: "medio" },
  { q: "¿Compositor de 'El lago de los cisnes'?", options: ["Tchaikovsky", "Stravinsky", "Prokofiev", "Glinka"], correct: 0, difficulty: "medio" },

  // --- [151-200] TEORÍA MUSICAL AVANZADA Y LENGUAJE ---
  { q: "¿Qué figura musical representa un tercio de un pulso en un compás simple?", options: ["Semicorchea", "Tresillo", "Corchea con puntillo", "Fusa"], correct: 1, difficulty: "medio" },
  { q: "¿Qué significa 'Da Capo' (D.C.) en una partitura?", options: ["Subir el volumen", "Terminar la canción", "Volver al principio", "Ir al estribillo"], correct: 2, difficulty: "medio" },
  { q: "¿Qué término indica que se debe ir disminuyendo la velocidad poco a poco?", options: ["Crescendo", "Ritardando", "Staccato", "A tempo"], correct: 1, difficulty: "medio" },
  { q: "¿Cómo se llama la nota que da nombre a una escala (el Grado I)?", options: ["Dominante", "Sensible", "Tónica", "Subdominante"], correct: 2, difficulty: "facil" },
  { q: "¿Qué grado de la escala es la 'Dominante'?", options: ["El tercero (III)", "El cuarto (IV)", "El quinto (V)", "El séptimo (VII)"], correct: 2, difficulty: "medio" },
  { q: "¿Cuál es la armadura que tiene un solo sostenido (Fa#)?", options: ["Do Mayor", "Sol Mayor", "Re Mayor", "Fa Mayor"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué símbolo anula el efecto de un sostenido o un bemol?", options: ["El doble sostenido", "El calderón", "La ligadura", "El becuadro"], correct: 3, difficulty: "facil" },
  { q: "¿Qué intervalo hay de Do a Sol?", options: ["Tercera", "Cuarta", "Quinta", "Sexta"], correct: 2, difficulty: "facil" },
  { q: "¿Cómo se llama el acorde formado por cuatro notas (añadiendo la séptima)?", options: ["Tríada", "Cuatríada", "Quinta vacía", "Acorde de paso"], correct: 1, difficulty: "medio" },
  { q: "¿Qué estilo musical usa intensamente la polirritmia (varios ritmos a la vez)?", options: ["Pop", "Música clásica europea", "Música tradicional africana", "Country"], correct: 2, difficulty: "medio" },
  { q: "¿Qué es un arpegio?", options: ["Tocar un acorde nota por nota", "Tocar muy rápido", "Un error de afinación", "Un silencio largo"], correct: 0, difficulty: "facil" },
  { q: "¿Qué significa 'Staccato'?", options: ["Tocar notas muy ligadas", "Tocar notas cortas y separadas", "Subir el tono", "Bajar el volumen"], correct: 1, difficulty: "medio" },
  { q: "¿Qué clave se utiliza para los sonidos más agudos?", options: ["Clave de Fa", "Clave de Sol", "Clave de Do en 3ª", "Clave de Do en 4ª"], correct: 1, difficulty: "facil" },
  { q: "¿Qué indica la ligadura de prolongación?", options: ["Suma la duración de dos notas iguales", "Se debe respirar", "Se toca más fuerte", "Termina la frase"], correct: 0, difficulty: "medio" },
  { q: "¿Qué es la 'Sensible' en una escala mayor?", options: ["El 1er grado", "El 3er grado", "El 5º grado", "El 7º grado"], correct: 3, difficulty: "dificil" },
  { q: "¿Cuántas semicorcheas caben en una nota Blanca?", options: ["4", "8", "16", "32"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es el 'Tempo'?", options: ["El volumen", "El carácter", "La velocidad de la música", "El instrumento"], correct: 2, difficulty: "facil" },
  { q: "¿Qué acorde es relativo menor de Sol Mayor?", options: ["Mi Menor", "La Menor", "Si Menor", "Do Menor"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué figura es la más larga de las siguientes?", options: ["Blanca", "Redonda", "Cuadrada", "Breve"], correct: 1, difficulty: "facil" },
  { q: "¿Qué significa 'Atonalidad'?", options: ["Cantar afinado", "Música sin un centro tonal definido", "Un coro sin voces", "Tocar muy grave"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué compás es 2/4?", options: ["Binario", "Ternario", "Cuaternario", "Irregular"], correct: 0, difficulty: "medio" },
  { q: "¿Qué distancia hay entre Mi y Fa natural?", options: ["Un tono", "Un semitono", "Dos tonos", "Ninguna"], correct: 1, difficulty: "medio" },
  { q: "¿Cómo se llama el silencio que dura lo mismo que una figura de un tiempo?", options: ["Silencio de redonda", "Silencio de negra", "Silencio de corchea", "Silencio de blanca"], correct: 1, difficulty: "facil" },
  { q: "¿Qué nota obtenemos si bajamos medio tono a un Si natural?", options: ["Do", "La", "Sib (Si bemol)", "Si# (Si sostenido)"], correct: 2, difficulty: "medio" },
  { q: "¿Qué es la dinámica en música?", options: ["La velocidad", "El grado de intensidad o volumen", "La afinación", "El estilo"], correct: 1, difficulty: "medio" },
  { q: "¿Qué significa D.S. al Coda?", options: ["Terminar ya", "Repetir desde el estribillo", "Desde el signo (Segno) hasta la Coda", "Tocar más fuerte"], correct: 2, difficulty: "dificil" },
  { q: "¿Qué acorde se forma con Re, Fa# y La?", options: ["Re Menor", "Re Mayor", "Re Aumentado", "Re Disminuido"], correct: 1, difficulty: "dificil" },
  { q: "¿Cuál es la nota más aguda de las siguientes?", options: ["C2", "C3", "C4", "C5"], correct: 3, difficulty: "facil" },
  { q: "¿Qué es un 'BPM'?", options: ["Golpes por minuto", "Bajos por minuto", "Bandas por mes", "Buena pulsación musical"], correct: 0, difficulty: "facil" },
  { q: "¿Qué significa 'A tempo'?", options: ["Tocar más rápido", "Volver a la velocidad original", "Hacer una pausa", "Tocar en silencio"], correct: 1, difficulty: "medio" },
  { q: "¿Qué intervalo hay de Sol a Do?", options: ["Segunda", "Tercera", "Cuarta", "Quinta"], correct: 2, difficulty: "medio" },
  { q: "¿Qué es un 'Mordente'?", options: ["Un adorno musical rápido", "Un tipo de afinador", "Una púa rota", "Un acorde triste"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué estructura tiene una escala mayor?", options: ["T-ST-T-T-ST-T-T", "T-T-ST-T-T-T-ST", "ST-T-T-T-ST-T-T", "T-T-T-ST-T-T-ST"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué nota es equivalente enarmónicamente a Do#?", options: ["Reb", "Mib", "Si#", "Fab"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué tipo de acorde es Do-Mib-Sol?", options: ["Mayor", "Aumentado", "Disminuido", "Menor"], correct: 3, difficulty: "dificil" },
  { q: "¿Qué es una síncopa?", options: ["Acentuar una parte débil del compás", "Tocar sin ritmo", "Desmayarse cantando", "Un efecto de guitarra"], correct: 0, difficulty: "medio" },
  { q: "¿Qué indican dos barras verticales al final de un pentagrama?", options: ["Sube el volumen", "Repetición", "Final de la pieza", "Cambio de clave"], correct: 2, difficulty: "facil" },
  { q: "¿Cuál es la distancia de una octava?", options: ["5 tonos", "6 tonos", "7 tonos", "8 tonos"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es la 'Clave' en percusión latina?", options: ["Un cantante", "Un ritmo base de 5 golpes", "Un piano", "Un bajo"], correct: 1, difficulty: "medio" },
  { q: "¿Qué figura tiene un corchete (rabito)?", options: ["Negra", "Corchea", "Semicorchea", "Blanca"], correct: 1, difficulty: "facil" },
  { q: "¿Cuántos bemoles tiene la armadura de Fa Mayor?", options: ["0", "1", "2", "3"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué grado es la subdominante?", options: ["I", "II", "IV", "V"], correct: 2, difficulty: "medio" },
  { q: "¿Qué intervalo forma la 'quinta del lobo' o tritono?", options: ["Quinta justa", "Cuarta aumentada / Quinta disminuida", "Sexta menor", "Tercera mayor"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué indica la palabra 'Ritardando'?", options: ["Más volumen", "Menos volumen", "Más velocidad", "Menos velocidad progresivamente"], correct: 3, difficulty: "facil" },
  { q: "¿Qué es el cifrado americano?", options: ["Un código secreto", "Usar letras de la A a la G para las notas", "Una técnica vocal", "Un ritmo de batería"], correct: 1, difficulty: "facil" },
  { q: "¿Qué nota corresponde a la letra 'E'?", options: ["Do", "Re", "Mi", "Fa"], correct: 2, difficulty: "facil" },
  { q: "¿Qué compás tiene 3 tiempos de negra?", options: ["2/4", "3/4", "4/4", "6/8"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es el 'Pitch'?", options: ["El volumen", "El ritmo", "La altura o tono de una nota", "El instrumento"], correct: 2, difficulty: "medio" },
  { q: "¿Qué instrumento lee en clave de Do en 3ª línea?", options: ["Violín", "Viola", "Violonchelo", "Contrabajo"], correct: 1, difficulty: "dificil" },
  { q: "¿Cuál de estos acordes es una tríada mayor?", options: ["Do-Mi-Sol", "Do-Mib-Sol", "Do-Mi-Sol#", "Do-Mib-Solb"], correct: 0, difficulty: "facil" },

  // --- [201-250] HISTORIA DEL ROCK, POP, INDIE Y METAL ---
  { q: "¿De qué ciudad son originarios los hermanos Gallagher (Oasis)?", options: ["Londres", "Liverpool", "Manchester", "Glasgow"], correct: 2, difficulty: "medio" },
  { q: "¿Cómo se llama el icónico álbum de Nirvana con un bebé en la portada?", options: ["In Utero", "Bleach", "Nevermind", "MTV Unplugged"], correct: 2, difficulty: "facil" },
  { q: "¿Quién compuso y cantó 'Space Oddity'?", options: ["Elton John", "Freddie Mercury", "David Bowie", "Mick Jagger"], correct: 2, difficulty: "facil" },
  { q: "¿Qué banda lanzó el álbum 'Appetite for Destruction'?", options: ["Aerosmith", "Mötley Crüe", "Guns N' Roses", "Def Leppard"], correct: 2, difficulty: "medio" },
  { q: "¿Quién cantaba 'Superstition' y 'Isn't She Lovely'?", options: ["Ray Charles", "Stevie Wonder", "James Brown", "Marvin Gaye"], correct: 1, difficulty: "facil" },
  { q: "¿Cómo se llama el cantante de U2?", options: ["Sting", "Bono", "The Edge", "Bruce Springsteen"], correct: 1, difficulty: "facil" },
  { q: "¿De qué banda fue vocalista Thom Yorke?", options: ["Coldplay", "Blur", "Radiohead", "Muse"], correct: 2, difficulty: "medio" },
  { q: "¿En qué año fue asesinado John Lennon?", options: ["1970", "1975", "1980", "1985"], correct: 2, difficulty: "dificil" },
  { q: "¿Quién tocó el himno de EE.UU. con su guitarra en Woodstock '69?", options: ["Eric Clapton", "Carlos Santana", "Jimi Hendrix", "Pete Townshend"], correct: 2, difficulty: "medio" },
  { q: "¿Qué banda toca la famosa canción 'Hotel California'?", options: ["The Byrds", "The Eagles", "The Beach Boys", "The Doors"], correct: 1, difficulty: "facil" },
  { q: "¿Cómo se llamaba el baterista de Metallica desde sus inicios?", options: ["Lars Ulrich", "Dave Grohl", "Tommy Lee", "Joey Jordison"], correct: 0, difficulty: "medio" },
  { q: "¿Cuál es el nombre real de Elton John?", options: ["Reginald Kenneth Dwight", "John Roy", "Elton B. Smith", "Arthur John"], correct: 0, difficulty: "dificil" },
  { q: "¿De dónde es originaria la cantante Björk?", options: ["Suecia", "Noruega", "Islandia", "Dinamarca"], correct: 2, difficulty: "medio" },
  { q: "¿Qué banda es famosa por pioneros de la música electrónica con el álbum 'Autobahn'?", options: ["Depeche Mode", "Daft Punk", "Kraftwerk", "New Order"], correct: 2, difficulty: "dificil" },
  { q: "¿Quién cantaba 'Losing My Religion'?", options: ["R.E.M.", "U2", "The Cure", "The Smiths"], correct: 0, difficulty: "facil" },
  { q: "¿Qué banda lideraba el cantante Morrissey?", options: ["Joy Division", "The Smiths", "The Cure", "Depeche Mode"], correct: 1, difficulty: "medio" },
  { q: "¿Cómo se llama el guitarrista de los Red Hot Chili Peppers (más icónico)?", options: ["John Frusciante", "Dave Navarro", "Flea", "Chad Smith"], correct: 0, difficulty: "medio" },
  { q: "¿Qué banda sacó el álbum 'Rumours' en 1977?", options: ["Fleetwood Mac", "The Eagles", "ABBA", "Queen"], correct: 0, difficulty: "medio" },
  { q: "¿Cuál es el nombre real de Freddie Mercury?", options: ["Frederick Bulsara", "Farrokh Bulsara", "Fred Mercury", "Faisal Bulsara"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué banda compuso 'Under the Bridge'?", options: ["Nirvana", "Red Hot Chili Peppers", "Pearl Jam", "Foo Fighters"], correct: 1, difficulty: "facil" },
  { q: "¿Quién compuso la canción 'Creep'?", options: ["Oasis", "Blur", "Radiohead", "Pulp"], correct: 2, difficulty: "facil" },
  { q: "¿Quién cantaba 'Sweet Child O' Mine'?", options: ["Axl Rose", "Jon Bon Jovi", "Steven Tyler", "Sebastian Bach"], correct: 0, difficulty: "facil" },
  { q: "¿Cuál fue el primer sencillo de The Beatles?", options: ["Help!", "Hey Jude", "Love Me Do", "Yesterday"], correct: 2, difficulty: "dificil" }, 
  { q: "¿Qué cantante inventó el paso de baile 'Moonwalk'?", options: ["James Brown", "Prince", "Michael Jackson", "Usher"], correct: 2, difficulty: "facil" },
  { q: "¿Quién es el vocalista de Arctic Monkeys?", options: ["Alex Turner", "Julian Casablancas", "Damon Albarn", "Liam Gallagher"], correct: 0, difficulty: "medio" },
  { q: "¿Qué banda virtual fue creada por Damon Albarn?", options: ["Daft Punk", "Gorillaz", "The Strokes", "Blur"], correct: 1, difficulty: "medio" },
  { q: "¿Quién cantaba 'Livin' on a Prayer'?", options: ["Aerosmith", "Guns N' Roses", "Bon Jovi", "Europe"], correct: 2, difficulty: "facil" },
  { q: "¿En qué década nació el movimiento Punk?", options: ["1950s", "1960s", "1970s", "1990s"], correct: 2, difficulty: "medio" },
  { q: "¿De qué banda fue vocalista Robert Plant?", options: ["The Rolling Stones", "The Who", "Led Zeppelin", "Black Sabbath"], correct: 2, difficulty: "medio" },
  { q: "¿Qué banda es famosa por usar maquillaje blanco y negro (The Demon, Starchild...)?", options: ["Slipknot", "KISS", "Misfits", "Ghost"], correct: 1, difficulty: "facil" },
  { q: "¿Quién era la voz principal de The Police?", options: ["Bono", "Sting", "Phil Collins", "Peter Gabriel"], correct: 1, difficulty: "facil" },
  { q: "¿Qué banda británica está formada por los hermanos Angus y Malcolm Young?", options: ["AC/DC", "Def Leppard", "Judas Priest", "Motörhead"], correct: 0, difficulty: "medio" },
  { q: "¿Quién canta 'Back to Black'?", options: ["Lady Gaga", "Amy Winehouse", "Adele", "Sia"], correct: 1, difficulty: "facil" },
  { q: "¿Cómo se llama el festival mundial benéfico que organizó Bob Geldof en 1985?", options: ["Woodstock", "Coachella", "Live Aid", "Glastonbury"], correct: 2, difficulty: "medio" },
  { q: "¿Qué banda canta 'Don't Stop Believin''?", options: ["Journey", "Queen", "Toto", "Boston"], correct: 0, difficulty: "facil" },
  { q: "¿Qué rapero protagonizó la película '8 Mile'?", options: ["Tupac", "Snoop Dogg", "Eminem", "Dr. Dre"], correct: 2, difficulty: "facil" },
  { q: "¿Qué artista femenina canta 'Wrecking Ball'?", options: ["Taylor Swift", "Miley Cyrus", "Katy Perry", "Ariana Grande"], correct: 1, difficulty: "facil" },
  { q: "¿Qué banda popularizó el tema 'Karma Chameleon'?", options: ["Culture Club", "Duran Duran", "Spandau Ballet", "Tears for Fears"], correct: 0, difficulty: "medio" },
  { q: "¿De qué país es originaria la banda Rammstein?", options: ["Alemania", "Suecia", "Finlandia", "Noruega"], correct: 0, difficulty: "facil" },
  { q: "¿Qué cantante pop es conocida como 'La Reina del Pop'?", options: ["Whitney Houston", "Madonna", "Britney Spears", "Lady Gaga"], correct: 1, difficulty: "facil" },
  { q: "¿Quién fue el vocalista de Linkin Park?", options: ["Chris Cornell", "Chester Bennington", "Scott Weiland", "Layne Staley"], correct: 1, difficulty: "facil" },
  { q: "¿Qué banda lidera Dave Grohl tras la muerte de Kurt Cobain?", options: ["Audioslave", "Queens of the Stone Age", "Foo Fighters", "Tenacious D"], correct: 2, difficulty: "facil" },
  { q: "¿Qué legendario guitarrista tiene el apodo 'Slowhand' (Mano lenta)?", options: ["Jeff Beck", "Eric Clapton", "Mark Knopfler", "David Gilmour"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué banda lanzó el álbum 'Master of Puppets'?", options: ["Megadeth", "Slayer", "Metallica", "Anthrax"], correct: 2, difficulty: "facil" },
  { q: "¿Qué canción de Luis Fonsi rompió todos los récords de YouTube en 2017?", options: ["Bailando", "Despacito", "Mi Gente", "Danza Kuduro"], correct: 1, difficulty: "facil" },
  { q: "¿Quién era la voz de The Cranberries?", options: ["Sinead O'Connor", "Dolores O'Riordan", "Shirley Manson", "Gwen Stefani"], correct: 1, difficulty: "medio" },
  { q: "¿Qué grupo español cantaba 'Entre dos tierras'?", options: ["Estopa", "Mecano", "Héroes del Silencio", "Los Del Río"], correct: 2, difficulty: "facil" }, 
  { q: "¿Cómo se llama el líder de la banda The Cure?", options: ["Ian Curtis", "Robert Smith", "Simon Le Bon", "Martin Gore"], correct: 1, difficulty: "medio" },
  { q: "¿Qué cantante femenina rompió récords con 'I Will Always Love You'?", options: ["Celine Dion", "Whitney Houston", "Mariah Carey", "Aretha Franklin"], correct: 1, difficulty: "facil" },
  { q: "¿Qué famoso rapero fue asesinado en Las Vegas en 1996?", options: ["Notorious B.I.G.", "Eazy-E", "Tupac Shakur", "Mac Miller"], correct: 2, difficulty: "medio" },

  // --- [251-300] INSTRUMENTOS, LUTHERÍA, ESTUDIO Y PRODUCCIÓN ---
  { q: "¿Qué es un Luthier?", options: ["Un tipo de violín", "Un artesano que construye/repara instrumentos", "Un efecto de voz", "Un cantante de ópera"], correct: 1, difficulty: "facil" },
  { q: "¿Qué madera se usa típicamente para la tapa armónica de las guitarras acústicas?", options: ["Abeto", "Ébano", "Caoba", "Pino"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué significan las siglas DAW en producción musical?", options: ["Digital Audio Workstation", "Direct Audio Wave", "Digital Acoustic Wave", "Dual Audio Window"], correct: 0, difficulty: "medio" },
  { q: "¿Cuál de estos es un programa DAW?", options: ["Photoshop", "Excel", "Ableton Live", "AutoCAD"], correct: 2, difficulty: "facil" },
  { q: "¿Qué es la 'Latencia' al grabar audio?", options: ["El volumen máximo", "El retraso de tiempo desde que tocas hasta que suena", "El eco", "La afinación"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es un cable XLR?", options: ["Cable de carga USB", "Cable de vídeo", "Cable balanceado típico de micrófono", "Cable de altavoz pasivo"], correct: 2, difficulty: "medio" },
  { q: "¿Qué es el 'Phantom Power' (+48V)?", options: ["Energía para micros de condensador", "Un pedal de distorsión", "Un amplificador de 48 vatios", "Una marca de guitarras"], correct: 0, difficulty: "dificil" },
  { q: "¿Para qué sirve un 'Compresor' de audio?", options: ["Afinar la voz", "Igualar los picos de volumen (rango dinámico)", "Añadir eco", "Cambiar el formato a MP3"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué hace la 'Ecualización' (EQ)?", options: ["Sube el volumen general", "Corta o realza frecuencias específicas (graves/agudos)", "Añade coros", "Elimina el ruido de fondo"], correct: 1, difficulty: "medio" },
  { q: "¿Cuál es el rango de frecuencias que el oído humano joven puede escuchar?", options: ["0 Hz - 10 kHz", "20 Hz - 20 kHz", "100 Hz - 50 kHz", "50 Hz - 100 kHz"], correct: 1, difficulty: "medio" },
  { q: "¿Qué diferencia a un micrófono dinámico de uno de condensador?", options: ["Es más sensible y frágil", "Es más robusto y soporta más volumen sin distorsionar", "Necesita electricidad extra", "Solo graba graves"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué es un micrófono con patrón 'Cardioide'?", options: ["Capta el sonido en forma de corazón (frontal)", "Capta en 360 grados", "Capta solo los latidos del corazón", "No capta sonido"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué significa MIDI?", options: ["Music In Digital Internet", "Musical Instrument Digital Interface", "Mini Input Data Interface", "Microphone Input Direct"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es la 'Reverb' (Reverberación)?", options: ["Un eco lejano", "La persistencia del sonido en un espacio cerrado", "Un cambio de tono", "Un fallo del cable"], correct: 1, difficulty: "facil" },
  { q: "¿Para qué sirve una 'Interfaz de Audio' o Tarjeta de Sonido?", options: ["Para escuchar música en Spotify", "Para convertir el sonido analógico en digital hacia el PC", "Para afinar la guitarra", "Para encender el PC"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es el 'Master' en un estudio de grabación?", options: ["El director del estudio", "El canal de salida principal donde se mezcla todo", "El disco duro", "Un instrumento"], correct: 1, difficulty: "medio" },
  { q: "¿Qué son los 'Monitores de estudio'?", options: ["Las pantallas de ordenador", "Altavoces planos que no colorean el sonido", "Cámaras de vigilancia", "Auriculares Bluetooth"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es un archivo WAV?", options: ["Un vídeo comprimido", "Un formato de audio sin compresión (alta calidad)", "Un formato de audio muy ligero", "Una partitura digital"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es el MP3?", options: ["Un formato de audio comprimido con pérdida de calidad", "Un formato de vídeo", "Un instrumento", "Un cable"], correct: 0, difficulty: "facil" },
  { q: "¿Qué es un teclado controlador MIDI?", options: ["Un teclado que tiene altavoces propios", "Un teclado que solo envía datos al PC, sin sonido propio", "Un piano de cola", "Un sintetizador analógico"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es el 'Feedback' o Acople?", options: ["Cuando el público aplaude", "El pitido cuando un micro capta el sonido de su propio altavoz", "Un efecto de eco", "Un error del PC"], correct: 1, difficulty: "facil" },
  { q: "¿Cómo se llama el tubo de metal o cristal que usan los guitarristas en el dedo?", options: ["Slide (o Bottleneck)", "Cejilla", "Púa", "Traste"], correct: 0, difficulty: "medio" },
  { q: "¿Qué es una pastilla 'Humbucker'?", options: ["Una pastilla simple", "Una pastilla de guitarra doble que cancela el ruido eléctrico", "Una batería", "Un pedal de bajo"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué es un bajo 'activo'?", options: ["Uno que se mueve mucho", "Uno que necesita una pila (preamplificador interno)", "Uno sin trastes", "Uno de 6 cuerdas"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es un 'Rack' de batería?", options: ["Las baquetas", "Una estructura metálica para colgar los tambores y platos", "La alfombra", "El asiento del baterista"], correct: 1, difficulty: "medio" },
  { q: "¿Qué marca de platillos de batería es de las más antiguas y famosas del mundo?", options: ["Fender", "Zildjian", "Yamaha", "Roland"], correct: 1, difficulty: "medio" },
  { q: "¿Qué son las 'escobillas' en batería?", options: ["Para limpiar los platos", "Baquetas de hilos de metal/plástico para tocar suave (Jazz)", "Un tipo de pedal", "Un soporte"], correct: 1, difficulty: "facil" },
  { q: "¿Cuántos pedales suele tener un arpa sinfónica moderna?", options: ["0", "3", "5", "7"], correct: 3, difficulty: "dificil" },
  { q: "¿Cómo se llaman las cuerdas de la viola de agudo a grave?", options: ["Mi, La, Re, Sol", "La, Re, Sol, Do", "Sol, Re, La, Mi", "Do, Sol, Re, La"], correct: 1, difficulty: "dificil" },
  { q: "¿Cómo se llama el instrumento de viento madera más pequeño y agudo de la orquesta?", options: ["Oboe", "Clarinete", "Flautín (Piccolo)", "Fagot"], correct: 2, difficulty: "medio" },
  { q: "¿Qué efecto es el 'Flanger'?", options: ["Un filtro que suena como el motor de un avión a reacción", "Un eco infinito", "Una distorsión sucia", "Un cambio de afinación"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué es el Auto-Tune?", options: ["Un robot que canta", "Un software que corrige la afinación de la voz automáticamente", "Un amplificador de guitarra", "Un micrófono"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es el 'Clipping' o picar en rojo?", options: ["Saturación digital destructiva porque la señal entra muy fuerte", "Cortar un trozo de audio", "Un ritmo latino", "Una púa especial"], correct: 0, difficulty: "dificil" },
  { q: "¿Cómo se llama el palo usado para tocar el violonchelo?", options: ["Baqueta", "Maza", "Arco", "Vara"], correct: 2, difficulty: "facil" },
  { q: "¿Qué es la 'Cejilla' o 'Capotraste'?", options: ["La cabeza del mástil", "Un accesorio para acortar las cuerdas y subir el tono", "Una pastilla", "Un cable"], correct: 1, difficulty: "facil" },
  { q: "¿Qué es el 'Truss rod' o Alma de la guitarra?", options: ["El puente", "La varilla metálica dentro del mástil para ajustar su curvatura", "Las clavijas", "El barniz"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué es un puente flotante (Ej: Floyd Rose)?", options: ["Un puente que permite mover la palanca hacia arriba y hacia abajo", "Un puente de madera", "Un puente que se quita fácil", "Un tipo de afinador"], correct: 0, difficulty: "medio" },
  { q: "¿Qué significa 'Afinación Drop D' en guitarra?", options: ["Afinar todas las cuerdas un tono abajo", "Bajar la 6ª cuerda (Mi) un tono entero hasta Re", "Subir la 1ª cuerda", "Afinar al revés"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué es un cable 'Speakon'?", options: ["Un cable de guitarra estándar", "Un cable de gran potencia para conectar amplificadores a altavoces", "Un cable USB", "Un cable MIDI"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué significa 'Bypass' en un pedal de efecto?", options: ["Que el pedal está roto", "Que la señal de audio pasa limpia sin ser afectada por el pedal", "Que suena el doble de fuerte", "Que hace eco"], correct: 1, difficulty: "medio" },
  { q: "¿Qué parte de la baqueta golpea el parche?", options: ["El cuello", "El cuerpo", "La bellota o punta", "La base"], correct: 2, difficulty: "facil" },
  { q: "¿Qué es la 'Frecuencia de Muestreo' estándar de un CD de audio?", options: ["44.1 kHz", "48 kHz", "96 kHz", "192 kHz"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué es el 'Overdubbing'?", options: ["Cantar muy alto", "Grabar una capa de audio nueva sobre otra ya existente", "Borrar la pista", "Bajar el volumen"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es el 'Tapping'?", options: ["Bailar claqué", "Tocar el piano", "Pulsar las cuerdas de la guitarra con los dedos de la mano derecha (sin púa)", "Afilar la púa"], correct: 2, difficulty: "medio" },
  { q: "¿Qué instrumento rítmico consiste en un cajón de madera sobre el que uno se sienta?", options: ["Bongó", "Conga", "Cajón flamenco", "Timbal"], correct: 2, difficulty: "facil" },
  { q: "¿Qué instrumento es el 'Fagot'?", options: ["Un tambor gigante", "Un viento-madera de registro grave", "Una trompeta pequeña", "Un teclado"], correct: 1, difficulty: "medio" },
  { q: "¿Qué es un 'Pad' en producción musical?", options: ["Un sonido sintetizado atmosférico y sostenido de fondo", "Un golpe seco", "Un silencio", "Una guitarra acústica"], correct: 0, difficulty: "dificil" },
  { q: "¿Cómo se llama la persona que diseña los sonidos y efectos en una película?", options: ["Compositor", "Diseñador de sonido / Foley", "Director", "Productor ejecutivo"], correct: 1, difficulty: "medio" },
  { q: "¿Qué empresa japonesa creó el mítico sintetizador DX7 y fabrica pianos y motos?", options: ["Korg", "Roland", "Yamaha", "Kawai"], correct: 2, difficulty: "facil" },
  { q: "¿Qué plataforma revolucionó la música en los 2000 al popularizar las descargas P2P?", options: ["Spotify", "Apple Music", "Napster", "YouTube"], correct: 2, difficulty: "medio" },

  // --- [301-365] TEORÍA PRO, ESTUDIO Y LEYENDAS (FIN DEL CICLO 365) ---
  { q: "¿Cómo se llama el Grado VI de una escala diatónica?", options: ["Dominante", "Sensible", "Submediante", "Mediante"], correct: 2, difficulty: "dificil" },
  { q: "¿Qué estructura tiene un acorde disminuido?", options: ["3ª Mayor y 5ª Justa", "3ª Menor y 5ª Disminuida", "3ª Mayor y 5ª Aumentada", "3ª Menor y 5ª Justa"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué estructura tiene un acorde aumentado?", options: ["3ª Menor y 5ª Disminuida", "3ª Mayor y 5ª Aumentada", "3ª Mayor y 5ª Justa", "3ª Menor y 5ª Justa"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué significa el símbolo 'C' grande al principio de un pentagrama?", options: ["Clave de Do", "Compás de 4/4 (Compasillo)", "Cambio de tono", "Crescendo"], correct: 1, difficulty: "medio" },
  { q: "¿En el círculo de quintas, qué tonalidad mayor viene justo a la derecha de Do Mayor?", options: ["Fa Mayor", "Re Mayor", "La Mayor", "Sol Mayor"], correct: 3, difficulty: "dificil" },
  { q: "¿Qué intervalo exacto hay entre Do y La?", options: ["Quinta", "Sexta", "Séptima", "Octava"], correct: 1, difficulty: "medio" },
  { q: "¿Qué fracción representa a la figura 'Fusa'?", options: ["1/8", "1/16", "1/32", "1/64"], correct: 2, difficulty: "dificil" },
  { q: "¿A qué figura equivale la duración de un tresillo de corcheas?", options: ["A una negra", "A una blanca", "A una corchea", "A una fusa"], correct: 0, difficulty: "dificil" },
  { q: "¿Cómo se llama la cadencia armónica que va del Grado V al Grado I?", options: ["Plagal", "Rota", "Perfecta", "Imperfecta"], correct: 2, difficulty: "dificil" },
  { q: "¿Cómo se llama la cadencia armónica que va del Grado IV al Grado I?", options: ["Plagal (Amén)", "Perfecta", "Rota", "Frigia"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué significa 'Rubato' en una interpretación musical?", options: ["Tocar sin instrumentos", "Tocar muy fuerte", "Acelerar o ralentizar el tempo con libertad expresiva", "Hacer silencios repentinos"], correct: 2, difficulty: "dificil" },
  { q: "¿Qué es una 'Modulación'?", options: ["Cambiar de instrumento", "Cambiar de tonalidad a mitad de la pieza", "Un error del amplificador", "Subir el volumen al máximo"], correct: 1, difficulty: "medio" },
  { q: "¿Qué textura musical tiene una melodía principal acompañada por acordes?", options: ["Monofonía", "Polifonía", "Homofonía", "Cacofonía"], correct: 2, difficulty: "dificil" },
  { q: "¿Qué es la enarmonía de Sol bemol (Solb)?", options: ["Fa sostenido (Fa#)", "La bemol (Lab)", "Mi natural", "Fa doble sostenido"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué tipo de compás es el 9/8?", options: ["Binario simple", "Ternario compuesto", "Cuaternario simple", "Amalgama irregular"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué nota ocupa el primer espacio (abajo) en la clave de Fa?", options: ["Do", "Mi", "Sol", "La"], correct: 3, difficulty: "dificil" },
  { q: "¿Qué indica la barra de repetición?", options: ["Símbolo de silencio", "Doble barra con dos puntos para repetir una sección", "Sube el tono un semitono", "Fin definitivo de la obra"], correct: 1, difficulty: "facil" },
  { q: "¿Para qué sirve un filtro 'High Pass' (Filtro Paso Alto) en un estudio?", options: ["Para dejar pasar los graves y cortar agudos", "Para cortar los graves y dejar pasar los agudos", "Para subir el volumen general", "Para afinar la voz"], correct: 1, difficulty: "medio" },
  { q: "¿Qué efecto se basa en crear repeticiones del sonido (eco)?", options: ["Chorus", "Phaser", "Delay", "Fuzz"], correct: 2, difficulty: "facil" },
  { q: "¿Qué es hacer 'Bouncing' o 'Bounce' en un DAW?", options: ["Bailar con la música", "Exportar la mezcla de varias pistas a un archivo estéreo de audio", "Borrar una pista por accidente", "Subir los graves"], correct: 1, difficulty: "dificil" },
  { q: "¿Cuál es la característica principal de un Micrófono de Cinta (Ribbon)?", options: ["Es indestructible", "Es ideal para bombos", "Es muy frágil y tiene un sonido muy cálido y vintage", "No necesita cable"], correct: 2, difficulty: "dificil" },
  { q: "¿Cómo se llama la cabeza de la guitarra donde van las clavijas en inglés?", options: ["Bridge", "Neck", "Fretboard", "Headstock"], correct: 3, difficulty: "dificil" },
  { q: "¿Cómo se dice 'Trastes' en inglés?", options: ["Strings", "Frets", "Pickups", "Knobs"], correct: 1, difficulty: "medio" },
  { q: "¿Qué nota añade la quinta cuerda extra en un bajo de 5 cuerdas moderno?", options: ["Un Do agudo", "Un Si grave (B)", "Un Fa grave", "Un Mi agudo"], correct: 1, difficulty: "dificil" },
  { q: "¿Cuál es el tambor de la batería que tiene patas y se apoya en el suelo?", options: ["Tom aéreo", "Caja", "Tom base (Floor Tom)", "Bombo"], correct: 2, difficulty: "facil" },
  { q: "¿Qué hace el pedal derecho del piano?", options: ["Sordina", "Acorta las notas", "Levanta los apagadores para que las notas resuenen (Sustain)", "Desplaza el teclado lateralmente"], correct: 2, difficulty: "medio" },
  { q: "¿Qué hace el pedal izquierdo del piano (Una corda)?", options: ["Sube el volumen", "Hace que el sonido sea más suave y apagado", "Hace eco", "Toca notas automáticas"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué instrumento electrónico se toca moviendo las manos en el aire sin tocarlo físicamente?", options: ["Sintetizador", "Theremin", "Melotrón", "Keytar"], correct: 1, difficulty: "medio" },
  { q: "¿Qué legendario teclado de los años 60 usaba cintas magnéticas reales para cada tecla?", options: ["Mellotron", "Hammond", "Rhodes", "Moog"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué significan las siglas VCO en un sintetizador analógico?", options: ["Virtual Computer Object", "Voltage-Controlled Oscillator", "Voice Chorus Output", "Volume Control Option"], correct: 1, difficulty: "dificil" },
  { q: "¿Cuántos canales de información puede transmitir un solo puerto MIDI?", options: ["8", "16", "32", "64"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué hace un 'Preamp' (Preamplificador) en una interfaz de audio?", options: ["Apaga el equipo", "Añade graves", "Amplifica la débil señal de un micrófono a 'nivel de línea'", "Borra el ruido"], correct: 2, difficulty: "medio" },
  { q: "¿Qué instrumento de viento metal no usa pistones ni válvulas, sino una vara deslizante?", options: ["Trompa", "Trombón", "Tuba", "Fliscorno"], correct: 1, difficulty: "facil" },
  { q: "¿Qué instrumento de percusión de la orquesta clásica SÍ puede afinar notas exactas?", options: ["Caja", "Timbales sinfónicos (Timpani)", "Gong", "Platos de choque"], correct: 1, difficulty: "medio" },
  { q: "¿Qué característica tiene un archivo MIDI?", options: ["Pesa muchísimo", "Contiene audio grabado en alta calidad", "No contiene audio, solo información (notas, duración, fuerza)", "Solo sirve para vídeos"], correct: 2, difficulty: "medio" },
  { q: "¿Qué efecto altera el volumen cíclicamente (arriba y abajo) sin cambiar la nota?", options: ["Vibrato", "Chorus", "Tremolo", "Delay"], correct: 2, difficulty: "dificil" },
  { q: "¿Cuál fue el primer vídeo musical emitido en MTV en 1981?", options: ["Thriller", "Video Killed the Radio Star", "Take On Me", "Money for Nothing"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué icónico artista es conocido como 'El Camaleón del Rock'?", options: ["Mick Jagger", "Freddie Mercury", "David Bowie", "Iggy Pop"], correct: 2, difficulty: "medio" },
  { q: "¿A qué famoso álbum pertenece la portada de un prisma separando la luz en un arcoíris?", options: ["The Wall", "Abbey Road", "The Dark Side of the Moon", "A Night at the Opera"], correct: 2, difficulty: "facil" },
  { q: "¿Qué famosa banda tiene como logo oficial una boca con la lengua roja sacada?", options: ["Aerosmith", "KISS", "The Rolling Stones", "Queen"], correct: 2, difficulty: "facil" },
  { q: "¿En qué año se lanzó el álbum 'Thriller' de Michael Jackson?", options: ["1979", "1982", "1985", "1989"], correct: 1, difficulty: "dificil" },
  { q: "¿Qué guitarrista de rock es además Doctor en Astrofísica?", options: ["Brian May (Queen)", "Jimmy Page (Led Zeppelin)", "Tom Morello (Tenacious D)", "Slash (GNR)"], correct: 0, difficulty: "medio" },
  { q: "¿Qué cantante asesinada trágicamente era conocida como 'La Reina del Tex-Mex'?", options: ["Gloria Estefan", "Celia Cruz", "Selena Quintanilla", "Shakira"], correct: 2, difficulty: "medio" },
  { q: "¿Quién compuso y grabó la versión original del clásico del rock 'Johnny B. Goode'?", options: ["Elvis Presley", "Jerry Lee Lewis", "Chuck Berry", "Little Richard"], correct: 2, difficulty: "facil" },
  { q: "¿Qué genio de la música clásica compuso la ópera 'La Flauta Mágica'?", options: ["Beethoven", "Mozart", "Wagner", "Puccini"], correct: 1, difficulty: "medio" },
  { q: "¿Qué compositor ruso creó la música para el ballet 'El Cascanueces'?", options: ["Tchaikovsky", "Stravinsky", "Rachmaninov", "Prokofiev"], correct: 0, difficulty: "medio" },
  { q: "¿Qué banda de Nu Metal es famosa por usar túnicas y terroríficas máscaras personalizadas?", options: ["Korn", "System of a Down", "Slipknot", "Limp Bizkit"], correct: 2, difficulty: "facil" },
  { q: "¿Qué cantante pop hizo historia usando un corsé cónico diseñado por Jean Paul Gaultier?", options: ["Cher", "Madonna", "Lady Gaga", "Kylie Minogue"], correct: 1, difficulty: "medio" },
  { q: "¿Qué cantautor canadiense es el compositor original de la famosísima canción 'Hallelujah'?", options: ["Jeff Buckley", "Bob Dylan", "Neil Young", "Leonard Cohen"], correct: 3, difficulty: "dificil" },
  { q: "¿En qué famoso grupo femenino comenzó su carrera Beyoncé?", options: ["TLC", "Spice Girls", "Destiny's Child", "The Pussycat Dolls"], correct: 2, difficulty: "facil" },
  { q: "¿Cuál es el verdadero nombre de Lady Gaga?", options: ["Stefani Germanotta", "Katheryn Hudson", "Elizabeth Grant", "Robyn Fenty"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué mítico club de Nueva York (cerrado en 2006) fue la cuna del punk estadounidense (Ramones, Blondie...)?", options: ["Studio 54", "CBGB", "The Cavern", "Whisky a Go Go"], correct: 1, difficulty: "dificil" },
  { q: "¿Cómo se llama el clásico modelo de guitarra Gibson que tiene una agresiva forma de 'V' invertida?", options: ["Explorer", "Firebird", "Flying V", "Les Paul"], correct: 2, difficulty: "medio" },
  { q: "¿A qué velocidad giran normalmente los discos de vinilo de formato grande (LP)?", options: ["45 RPM", "78 RPM", "33 1/3 RPM", "120 RPM"], correct: 2, difficulty: "dificil" },
  { q: "¿Quién fue el polémico bajista y figura icónica de los Sex Pistols?", options: ["John Lydon", "Sid Vicious", "Paul Simonon", "Dee Dee Ramone"], correct: 1, difficulty: "medio" },
  { q: "¿Quién era el líder, guitarrista y vocalista de The Clash?", options: ["Joe Strummer", "Mick Jones", "Paul Weller", "Billy Idol"], correct: 0, difficulty: "dificil" },
  { q: "¿Quién compuso el famosísimo vals 'El Danubio Azul'?", options: ["Richard Wagner", "Johann Strauss (hijo)", "Franz Liszt", "Johannes Brahms"], correct: 1, difficulty: "medio" },
  { q: "¿Quién de estos tres NO pertenecía al trío de 'Los Tres Tenores' de los años 90?", options: ["Luciano Pavarotti", "Plácido Domingo", "José Carreras", "Andrea Bocelli"], correct: 3, difficulty: "facil" },
  { q: "¿Qué legendario productor fue conocido como 'El Quinto Beatle'?", options: ["Rick Rubin", "Quincy Jones", "George Martin", "Phil Spector"], correct: 2, difficulty: "medio" },
  { q: "¿Qué banda fue formada por Dave Mustaine tras ser expulsado de Metallica?", options: ["Slayer", "Megadeth", "Anthrax", "Pantera"], correct: 1, difficulty: "medio" },
  { q: "¿Cómo se llama la técnica en la que el cantante produce una nota y a la vez silba otras por encima creando armonías?", options: ["Canto difónico", "Falsete", "Growl", "Scat"], correct: 0, difficulty: "dificil" },
  { q: "¿Qué rapero ha ganado más premios Grammy en la historia y es considerado un dios del Hip-Hop (Rap God)?", options: ["Tupac", "Snoop Dogg", "Eminem", "Jay-Z"], correct: 2, difficulty: "facil" },
  { q: "¿Qué es un acorde de 'Quinta vacía' o Power Chord (usado en Rock/Metal)?", options: ["Un acorde con tres notas", "Un acorde de dos notas (Tónica y Quinta) sin la tercera", "Un acorde mayor séptima", "Un acorde disminuido"], correct: 1, difficulty: "medio" },
  { q: "¿Cuál es el compás flamenco por excelencia, característico de bulerías y soleás?", options: ["Amalgama de 12 tiempos", "Compás de 4/4", "Compás de 3/4", "Compás de 5/8"], correct: 0, difficulty: "dificil" },
  { q: "¿A qué cantante de jazz estadounidense se la conocía como 'Lady Day'?", options: ["Ella Fitzgerald", "Billie Holiday", "Nina Simone", "Sarah Vaughan"], correct: 1, difficulty: "dificil" }
];
